name: Check Changelog


on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Check that CHANGELOG is touched
      run: |
        git diff remotes/origin/${{ github.base_ref }} --name-only | grep CHANGELOG.md
